### PR TITLE
Make sure the proper branch / tag of docs is being used from github.

### PR DESCRIPTION
**Pull request by ericbottard**
Some general cleanup of properties

Fixes spring-cloud/spring-cloud-dataflow-server-cloudfoundry/issues/181

### CODE REVIEW

**Comment by jvalkeal** [comment]
Looks like on a conceptual level use of branched/tagged version will not work.

- html will link directly to github with used address in asciidoc.
- pdf/epub will download images and embed those is a created doc.

As looking build log for a release at https://build.spring.io/download/SCD-CFBMASTER-JOB1/build_logs/SCD-CFBMASTER-JOB1-204.log

```
build	25-Aug-2016 18:22:27	[INFO] Deploying artifact: https://repo.spring.io/libs-staging-local/org/springframework/cloud/spring-cloud-dataflow-server-cloudfoundry-docs/1.0.0.RELEASE/spring-cloud-dataflow-server-cloudfoundry-docs-1.0.0.RELEASE.zip;zip.type=docs;zip.deployed=false
build	25-Aug-2016 18:22:28	[INFO] Artifactory Build Info Recorder: Deploying build info ...
build	25-Aug-2016 18:22:28	[INFO] Deploying build descriptor to: https://repo.spring.io/api/build
build	25-Aug-2016 18:22:30	[INFO] Build successfully deployed. Browse it in Artifactory under https://repo.spring.io/webapp/builds/Spring%20Cloud%20Data%20Flow%20-%20Server%20-%20Cloud%20Foundry%20-%20Master%20-%20Build%20Spring%20Cloud%20Data%20Admin%20CF/204
build	25-Aug-2016 18:22:30	[INFO] ------------------------------------------------------------------------
build	25-Aug-2016 18:22:30	[INFO] Reactor Summary:
build	25-Aug-2016 18:22:30	[INFO] 
build	25-Aug-2016 18:22:30	[INFO] spring-cloud-dataflow-server-cloudfoundry-parent .. SUCCESS [2.567s]
build	25-Aug-2016 18:22:30	[INFO] spring-cloud-starter-dataflow-server-cloudfoundry . SUCCESS [6.241s]
build	25-Aug-2016 18:22:30	[INFO] spring-cloud-dataflow-server-cloudfoundry ......... SUCCESS [4.734s]
build	25-Aug-2016 18:22:30	[INFO] spring-cloud-dataflow-server-cloudfoundry-docs .... SUCCESS [40.782s]
build	25-Aug-2016 18:22:30	[INFO] ------------------------------------------------------------------------
build	25-Aug-2016 18:22:30	[INFO] BUILD SUCCESS
build	25-Aug-2016 18:22:30	[INFO] ------------------------------------------------------------------------
build	25-Aug-2016 18:22:30	[INFO] Total time: 1:10.676s
build	25-Aug-2016 18:22:30	[INFO] Finished at: Thu Aug 25 18:22:30 UTC 2016
build	25-Aug-2016 18:22:30	[INFO] Final Memory: 162M/1354M
build	25-Aug-2016 18:22:30	[INFO] ------------------------------------------------------------------------
...
simple	25-Aug-2016 18:22:31	[RELEASE] Committing release version on branch 'master'
simple	25-Aug-2016 18:22:31	[RELEASE] Pushing tag: v1.0.0.RELEASE to url https://github.com/spring-cloud/spring-cloud-dataflow-admin-cloudfoundry.git
simple	25-Aug-2016 18:22:32	[RELEASE] This repository moved. Please use the new location:  https://github.com/spring-cloud/spring-cloud-dataflow-server-cloudfoundry.git
...
```
This build didn't use release branch but that would be pushed to github just before pushing a tag. What this means is that branch/tag doesn't exist in github when release build is done. 

We'd get away from it for html(is it's just linked and branch/tag will become available later) but pdf would fail to import those images. Also for html we should not use github as a CDN for images in a docs anyway.

**Comment by ericbottard** [comment]
Note that this is for server-cf which references scdf-core, so at the time we release server-cf, scdf-core has already been released, so the tag DOES exist. Or am I missing something?

I'm just automating things we're already doing. That being said, I agree we tend to abuse over-http includes and github cdn...

**Comment by jvalkeal** [comment]
well yes, sabby asked to comment on a generic level. we'd have this issue if cf docs would have their own images, or if we do this same dance in a dataflow core(imported asciidocs from there still point to master).

**Comment by jvalkeal** [comment]
Looks good, merging.

**Pull request merged**
