### PR TITLE
Add and document support for Docker resources

### PR DESCRIPTION
**Pull request by ericbottard**
Fixes https://github.com/spring-cloud/spring-cloud-dataflow-server-cloudfoundry/issues/287

### CODE REVIEW

**Comment by trisberg** [comment]
Not sure I understand the motivation for this feature unless we bind the services and provide instructions for configuring apps to use them. Without a binder there is no stream AFAIK. And launching a task with a docker image doesn't seem to work, I get this error:

```
java.io.FileNotFoundException: Docker Resource [docker:springcloudtask/timestamp-task:latest] cannot be resolved to absolute file path
```

Same image (`docker://springcloudtask/timestamp-task:latest`) works fine on the k8s server.

**Comment by ericbottard** [comment]
Note that we *do* bind the services. This is targeted at non-java apps mainly IMO (eg python apps) and so users would have to interpret binder properties in an ad-hoc fashion.

I'll need to look into the task issue (tested stream apps only)

**Comment by trisberg** [comment]
Ahh, you right, I see that we do bind the service - wonder why that didn't show up using `cf app test-ticktock-log`, so we should be able to set the boot properties for rabbit when deploying the stream apps

**Comment by trisberg** [comment]
I was able to get the binder configured by using the following properties fro my stream:

```
stream create ticktock --definition 'time --spring.rabbitmq.addresses=${vcap.services.rabbit.credentials.protocols.amqp.uri} | log --spring.rabbitmq.addresses=${vcap.services.rabbit.credentials.protocols.amqp.uri}'
```

**Comment by trisberg** [comment]
Two additional way to get this to work:

deployment property:

```
stream deploy ticktock --properties app.*.spring.rabbitmq.addresses=${vcap.services.rabbit.credentials.protocols.amqp.uris}
```

or as a common property for all stream apps:

```
cf set-env dataflow-server SPRING_APPLICATION_JSON '{"spring.cloud.dataflow.applicationProperties.stream.spring.rabbitmq.addresses": "${vcap.services.rabbit.credentials.protocols.amqp.uris}"}'
```

**Comment by ericbottard** [comment]
Duh!

Tasks are not supported atm and would require a change at the deployer-cf level anyway. I think it should not block that particular PR

**Comment by trisberg** [comment]
Not supported where - deployer / java client /CF itself?  I can merge this without this. Should we  also add a note to include a  common property for all stream apps for the binder?

**Comment by ericbottard** [comment]
Sorry. Supported in cf-deployer.

Le 20 mars 2017 9:54 PM, "Thomas Risberg" <notifications@github.com> a
écrit :

**Comment by ericbottard** [comment]
Created https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/issues/164 to track task+docker support.

This PR can be merged without it though

**Comment by trisberg** [comment]
Rebased and merged as commit 20040c1811cf92a0825f4ed151e3597f48c8b86b

Added a commit updating the docs

**Pull request closed without merging**
