### PR TITLE
Inherit from spring-boot-starter-parent

### PR DESCRIPTION
**Pull request by ericbottard**
Fixes https://github.com/spring-cloud/spring-cloud-dataflow-server-cloudfoundry/issues/202

### CODE REVIEW

**Comment by jvalkeal** [comment]
Hmm, well #202 talks about `spring-boot-parent`, title of this PR mentions `spring-cloud-starter-parent` and actual commit uses `spring-boot-starter-parent`.

**Comment by ericbottard** [comment]
I got the title wrong, sorry (edited).

I believe what we want is indeed spring-boot-starter-parent, as the rationale for this was explained to me to "use the same thing as what a user would get on start.spring.io".

cc @markpollack

**Comment by markpollack** [comment]
DO NOT MERGE.  Need to sort out some other issues with default values of application.properties first.

**Comment by ericbottard** [comment]
Closing.

Will issue a PR inspired by https://github.com/spring-cloud/spring-cloud-dataflow-server-kubernetes/pull/139 instead

**Pull request closed without merging**
