### PR TITLE
Update env-var's from upper to lower case

### PR DESCRIPTION
**Pull request by sabbyanandan**
- change all env-var's from upper -> lower
- add `config-server` instruction
- fix previously committed formatting issue .. see below

image

### CODE REVIEW

**Comment by ericbottard** [comment]
Verified that dotted props work against PEZ

**Comment by wilkinsona** [comment]
What's the motivation for moving to lower case environment variables? It's rather unconventional and, in  some environments, `.` is an illegal character in an environment variable.

**Comment by sabbyanandan** [comment]
Hi, @wilkinsona: There were recent discussions around Boot's limitation wrt handling "map of maps" properties and the ideal way to pass them to different runtime platforms such as Cloud Foundry. While iterating over few options, we discovered that lower-case + `.` as a combination that worked (_for CF; hence the PR in our CF-server_); however, we quickly also realized it is not the convention, so we are reverting the change via spring-cloud/spring-cloud-dataflow-server-cloudfoundry#135.

**Comment by wilkinsona** [comment]
Thanks for the info, @sabbyanandan. FWIW, I like your plan in #135.

**Pull request merged**
