### PR TITLE
Binding Redis to stream apps is needed

### PR DESCRIPTION
**Pull request by making**
for Analytics (ex. counter, field value counter)

### CODE REVIEW

**Comment by ericbottard** [comment]
It is needed, but it is not needed *for all apps*. As you stated, this is required only for analytics.
This is what [this section](https://github.com/spring-cloud/spring-cloud-dataflow-server-cloudfoundry/blob/master/spring-cloud-dataflow-server-cloudfoundry-docs/src/main/asciidoc/getting-started.adoc#provision-a-redis-service-instance-on-cloud-foundry) of the doc tried to explain:
> A redis instance is required for analytics apps, and would typically be bound to such apps when you create an analytics stream using the per-app-binding feature.

I would rather make that more clear than accept this PR as is

**Comment by ericbottard** [comment]
@making Any remark / advice on what should be improved in the docs, wrt to when/why redis is needed?

**Comment by making** [comment]
@ericbottard I agree redis should be bound only for analytics.
Actually, i had a problem when i was trying [Twitter Analytics Sample](https://github.com/spring-cloud/spring-cloud-dataflow-samples/tree/master/analytics/twitter-analytics) on PCF Dev.
I think remarking on this doc could be nice.

**Comment by ericbottard** [comment]
I understand. That sample is explicitly written for a local server usage, so that concern doesn't apply (and it would be awkward to modify mentioning Cloud Foundry there). Shall I close this issue?

**Comment by making** [comment]
@ericbottard 
OK.

I confirmed 

```
stream create tweets --definition "twitterstream --consumerKey=<CONSUMER_KEY> --consumerSecret=<CONSUMER_SECRET> --accessToken=<ACCESS_TOKEN> --accessTokenSecret=<ACCESS_TOKEN_SECRET> | log"
stream create --name tweetlang  --definition ":tweets.twitterstream > field-value-counter --fieldName=lang --name=language"
stream create --name tagcount --definition ":tweets.twitterstream > field-value-counter --fieldName=entities.hashtags.text --name=hashtags"
stream deploy --name tweetlang  --properties "app.field-value-counter.spring.cloud.deployer.cloudfoundry.services=redis"
stream deploy --name tagcount --properties "app.field-value-counter.spring.cloud.deployer.cloudfoundry.services=redis"
stream deploy --name tweets
```

worked well as for the Twitter Analytics Sample.

**Comment by ericbottard** [comment]
Cool, thanks @making

**Pull request closed without merging**
