### PR TITLE
Fix docs following stream/task split

### PR DESCRIPTION
**Pull request by ericbottard**
Fixes spring-cloud/spring-cloud-dataflow-server-cloudfoundry#165

### CODE REVIEW

**Comment by dturanski** [comment]
LGTM

**Comment by sabbyanandan** [comment]
+1; LGTM, too. There's still one other place in the docs we need this change - see [here](http://docs.spring.io/spring-cloud-dataflow-server-cloudfoundry/docs/current-SNAPSHOT/reference/htmlsingle/#getting-started-service-binding-at-application-level).

**Comment by ericbottard** [comment]
> There's still one other place in the docs we need this change - see here.

No, turns out this one needs to stay the same I believe. A bit confusing, but this is the way it works...

**Comment by markfisher** [comment]
almost makes it seem like the properties set at dataflow level should be prefixed as `app.stream.spring.cloud.deployer..` and `app.task.spring.cloud.deployer..` for consistency with the syntax at deploy-time app level.

**Comment by ericbottard** [comment]
Hmm, not sure. This is confusing as well:
- first of all, using the `app.` prefix in a non deployment-time context feels weird
- second, this looks like `stream` and `task` are app names, which they are not

**Comment by markfisher** [comment]
actually shouldn't those properties just be relying on the core dataflow approach?:
http://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#spring-cloud-dataflow-global-properties

**Comment by markfisher** [comment]
never mind - the properties that are set at the dataflow level are not "common application properties" since the CF dataflow server actually handles the mapping of those to the individual `ConfigurationProperties` instances (one for stream apps, one for task apps) as opposed to passing them along to all apps it deploys... and as for the properties passed at deploy time, that is simply targeting the actual property at the deployer level (where the `stream` and `task` qualifiers are not relevant). I'm afraid it is all a bit confusing, but all the more reason to make sure the documentation explains it as clearly as possible.

**Comment by cppwfs** [comment]
LGTM

**Pull request merged**
